version: "3"

networks:
  internal: { }

services:
  nginx:
    container_name: nginx
    build: nginx
    ports:
      - "8080:80"
    networks:
      - internal
  pg:
    container_name: pg_db
    build: pg
    networks:
      - internal
